INSERT INTO symbols (code, display_name, asset_class, scanner_code) VALUES
    ('FOREXCOM:EURUSD', 'Euro / US Dollar', 'forex', 'FX:EURUSD'),
    ('FOREXCOM:GBPUSD', 'British Pound / US Dollar', 'forex', 'FX:GBPUSD'),
    ('FOREXCOM:USDJPY', 'US Dollar / Japanese Yen', 'forex', 'FX:USDJPY'),
    ('FOREXCOM:AUDUSD', 'Australian Dollar / US Dollar', 'forex', 'FX:AUDUSD'),
    ('FOREXCOM:USDCHF', 'US Dollar / Swiss Franc', 'forex', 'FX:USDCHF'),
    ('FOREXCOM:USDCAD', 'US Dollar / Canadian Dollar', 'forex', 'FX:USDCAD'),
    ('FOREXCOM:NZDUSD', 'New Zealand Dollar / US Dollar', 'forex', 'FX:NZDUSD'),
    ('FOREXCOM:EURGBP', 'Euro / British Pound', 'forex', 'FX:EURGBP'),
    ('FOREXCOM:EURJPY', 'Euro / Japanese Yen', 'forex', 'FX:EURJPY'),
    ('FOREXCOM:GBPJPY', 'British Pound / Japanese Yen', 'forex', 'FX:GBPJPY'),
    ('FX_IDC:USDIDR', 'US Dollar / Indonesian Rupiah', 'forex', 'FX_IDC:USDIDR'),
    ('FX_IDC:USDCNH', 'US Dollar / Chinese Yuan', 'forex', 'FX_IDC:USDCNH'),
    ('FX_IDC:USDSGD', 'US Dollar / Singapore Dollar', 'forex', 'FX_IDC:USDSGD'),
    ('FX_IDC:USDMYR', 'US Dollar / Malaysian Ringgit', 'forex', 'FX_IDC:USDMYR'),
    ('FX_IDC:USDTHB', 'US Dollar / Thai Baht', 'forex', 'FX_IDC:USDTHB'),
    ('FOREXCOM:AUDJPY', 'Australian Dollar / Japanese Yen', 'forex', 'FX:AUDJPY'),
    ('FOREXCOM:EURCHF', 'Euro / Swiss Franc', 'forex', 'FX:EURCHF'),
    ('FOREXCOM:GBPCHF', 'British Pound / Swiss Franc', 'forex', 'FX:GBPCHF'),
    ('FOREXCOM:CADJPY', 'Canadian Dollar / Japanese Yen', 'forex', 'FX:CADJPY'),
    ('FOREXCOM:CHFJPY', 'Swiss Franc / Japanese Yen', 'forex', 'FX:CHFJPY'),
    ('FOREXCOM:EURCAD', 'Euro / Canadian Dollar', 'forex', 'FX:EURCAD'),
    ('FOREXCOM:EURAUD', 'Euro / Australian Dollar', 'forex', 'FX:EURAUD'),
    ('FOREXCOM:GBPAUD', 'British Pound / Australian Dollar', 'forex', 'FX:GBPAUD'),
    ('FOREXCOM:GBPCAD', 'British Pound / Canadian Dollar', 'forex', 'FX:GBPCAD'),
    ('FOREXCOM:AUDNZD', 'Australian Dollar / New Zealand Dollar', 'forex', 'FX:AUDNZD'),
    ('FOREXCOM:EURNZD', 'Euro / New Zealand Dollar', 'forex', 'FX:EURNZD'),
    ('FOREXCOM:NZDJPY', 'New Zealand Dollar / Japanese Yen', 'forex', 'FX:NZDJPY'),
    ('FOREXCOM:XAUUSD', 'Gold / US Dollar', 'commodity', 'FX:XAUUSD'),
    ('FOREXCOM:XAGUSD', 'Silver / US Dollar', 'commodity', 'FX:XAGUSD'),
    ('OANDA:XPTUSD', 'Platinum / US Dollar', 'commodity', 'OANDA:XPTUSD'),
    ('OANDA:XPDUSD', 'Palladium / US Dollar', 'commodity', 'OANDA:XPDUSD'),
    ('OANDA:SPX500USD', 'US 500 Index', 'index', 'OANDA:SPX500USD'),
    ('OANDA:NAS100USD', 'US Tech 100 Index', 'index', 'OANDA:NAS100USD'),
    ('OANDA:US30USD', 'US Wall Street 30 Index', 'index', 'OANDA:US30USD'),
    ('OANDA:DE30EUR', 'Germany 30 Index', 'index', 'OANDA:DE30EUR'),
    ('OANDA:UK100GBP', 'UK 100 Index', 'index', 'OANDA:UK100GBP'),
    ('OANDA:AU200AUD', 'Australia 200 Index', 'index', 'OANDA:AU200AUD'),
    ('TVC:VIX', 'VIX Volatility Index', 'index', 'TVC:VIX'),
    ('BITSTAMP:BTCUSD', 'Bitcoin / US Dollar', 'crypto', 'BITSTAMP:BTCUSD'),
    ('BITSTAMP:ETHUSD', 'Ethereum / US Dollar', 'crypto', 'BITSTAMP:ETHUSD'),
    ('BITSTAMP:SOLUSD', 'Solana / US Dollar', 'crypto', 'BITSTAMP:SOLUSD'),
    ('BITSTAMP:XRPUSD', 'XRP / US Dollar', 'crypto', 'BITSTAMP:XRPUSD'),
    ('BITSTAMP:DOGEUSD', 'Dogecoin / US Dollar', 'crypto', 'BITSTAMP:DOGEUSD'),
    ('BITSTAMP:ADAUSD', 'Cardano / US Dollar', 'crypto', 'BITSTAMP:ADAUSD'),
    ('BITSTAMP:LTCUSD', 'Litecoin / US Dollar', 'crypto', 'BITSTAMP:LTCUSD'),
    ('BITSTAMP:BCHUSD', 'Bitcoin Cash / US Dollar', 'crypto', 'BITSTAMP:BCHUSD'),
    ('NASDAQ:AAPL', 'Apple Inc', 'stock', 'NASDAQ:AAPL'),
    ('NASDAQ:MSFT', 'Microsoft Corp', 'stock', 'NASDAQ:MSFT'),
    ('NASDAQ:NVDA', 'NVIDIA Corp', 'stock', 'NASDAQ:NVDA'),
    ('NASDAQ:TSLA', 'Tesla Inc', 'stock', 'NASDAQ:TSLA'),
    ('NASDAQ:AMZN', 'Amazon.com Inc', 'stock', 'NASDAQ:AMZN'),
    ('NASDAQ:META', 'Meta Platforms Inc', 'stock', 'NASDAQ:META'),
    ('NASDAQ:GOOGL', 'Alphabet Inc', 'stock', 'NASDAQ:GOOGL'),
    ('NASDAQ:NFLX', 'Netflix Inc', 'stock', 'NASDAQ:NFLX'),
    ('NASDAQ:AMD', 'Advanced Micro Devices', 'stock', 'NASDAQ:AMD'),
    ('NYSE:JPM', 'JPMorgan Chase & Co', 'stock', 'NYSE:JPM'),
    ('NYSE:V', 'Visa Inc', 'stock', 'NYSE:V'),
    ('NYSE:KO', 'Coca-Cola Co', 'stock', 'NYSE:KO');
